addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
      - lib32z1-dev
      - libc6-dev-i386
      - g++-multilib
      - g++-4.9
language: cpp
sudo: false
compiler:
  - clang
before_script:
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - PATH="~/.local/bin:$PATH"
  - mkdir build-clang-opt && cd build-clang-opt
  - python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-clang-debug && cd build-clang-debug
  - python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc49-opt && cd build-clang-opt
  - CC="gcc-4.9" CXX="g++-4.9" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc49-debug && cd build-clang-debug
  - CC="gcc-4.9" CXX="g++-4.9" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..
