addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - lib32stdc++6
      - lib32z1-dev
      - libc6-dev-i386
      - g++-multilib
      - g++-5
      - g++-6
      - clang-3.8
language: cpp
sudo: false
compiler:
  - clang
before_script:
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - PATH="~/.local/bin:$PATH"
  - mkdir build-clang-opt && cd build-clang-opt
  - CC="clang-3.8" CXX="clang++-3.8" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-clang-debug && cd build-clang-debug
  - python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc5-opt && cd build-gcc5-opt
  - CC="gcc-5" CXX="g++-5" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc5-debug && cd build-gcc5-debug
  - CC="gcc-5" CXX="g++-5" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc6-opt && cd build-gcc6-opt
  - CC="gcc-6" CXX="g++-6" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc6-debug && cd build-gcc6-debug
  - CC="gcc-6" CXX="g++-6" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..
