git:
  depth: 3

sudo: false
language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: ['clang-3.8', 'lib32stdc++6', 'lib32z1-dev', 'libc6-dev-i386', 'linux-libc-dev:i386', 'g++-4.9-multilib']
      env:
        - PATH="~/.local/bin:$PATH"
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - os: linux
      dist: trusty
      sudo: false
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: ['clang-3.4', 'lib32stdc++6', 'lib32z1-dev', 'libc6-dev-i386', 'linux-libc-dev:i386', 'g++-4.9-multilib']
      env:
        - PATH="~/.local/bin:$PATH"
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: osx
      osx_image: xcode6.4
      sudo: true
      language: cpp
      env:
        - PATH="~/Library/Python/2.7/bin:$PATH"
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: linux
      dist: bionic
      sudo: false
      language: cpp
      addons:
        apt:
          packages: ['lib32stdc++6', 'lib32z1-dev', 'libc6-dev-i386', 'linux-libc-dev:i386', 'g++-multilib', 'clang']
      env:
        - PATH="~/.local/bin:$PATH"
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: linux
      dist: bionic
      sudo: false
      language: cpp
      addons:
        apt:
          packages: ['lib32stdc++6', 'lib32z1-dev', 'libc6-dev-i386', 'linux-libc-dev:i386', 'g++-multilib', 'g++']
      env:
        - PATH="~/.local/bin:$PATH"
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_script:
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - eval "${MATRIX_EVAL}"
  - eval "${CC} --version"
  - eval "${CXX} --version"

  - mkdir build-opt && cd build-opt
  - python ../configure.py --enable-optimize
  - ambuild
  - ./dist/testrunner
  - cd ..

  - mkdir build-debug && cd build-debug
  - python ../configure.py --enable-debug
  - ambuild
  - ./dist/testrunner
